import type {
  CreateImageGenerationInput,
  ImageGeneration,
  ImageGenerationRepository,
} from "@ai-platform/database";
import type { ImageProvider } from "@ai-platform/shared";
import type { AssetStore } from "./asset-store.js";

export interface ImageGenerationDeps {
  generationRepo: ImageGenerationRepository;
  assetStore: AssetStore;
  provider: ImageProvider;
}

/**
 * Records the pending row an API caller can poll immediately. Takes the repository's own
 * input shape rather than re-listing its fields: the tenant `projectId` and the requesting
 * `createdByUserId` (ADR-049) come from the caller's authenticated context, and inventing a
 * default for either here would attribute someone's spend to the wrong project.
 */
export async function createPendingImageGeneration(
  generationRepo: ImageGenerationRepository,
  input: CreateImageGenerationInput
): Promise<ImageGeneration> {
  return generationRepo.create(input);
}

/**
 * Runs the actual generation — designed to execute inside a job worker (docs/07 §1.6
 * "mock-provider parity": even the mock goes through the real async job system, not an
 * inline call), mirroring backend/packages/rag's `processDocumentIngestion` split.
 *
 * `projectId` is the tenant scope (ADR-049), carried in the job payload alongside the
 * generation id: every repository call below applies it in the SQL `WHERE`, so a job payload
 * naming another tenant's generation id resolves to nothing rather than to a row this worker
 * would then have to be trusted to reject.
 */
export async function processImageGeneration(
  deps: ImageGenerationDeps,
  projectId: string,
  generationId: string
): Promise<void> {
  const generation = await deps.generationRepo.get(projectId, generationId);
  if (!generation) throw new Error(`Unknown image generation "${generationId}" in project "${projectId}".`);

  /**
   * Cancelled while it was queued — ADR-122. `requestCancel` and the `cancelled` status existed
   * from the start and nothing ever observed them, so the state was unreachable and a user had no
   * way to stop work they had started. On a billed provider that is money spent after the person
   * asked for it to stop.
   */
  if (generation.cancelRequestedAt) {
    await deps.generationRepo.updateStatus(projectId, generationId, "cancelled", {
      errorMessage: "Cancelled before generation started.",
    });
    return;
  }

  // `incrementAttempt` counts attempts actually started, in SQL — so a generation retried by
  // pg-boss reads as several attempts rather than as one unusually slow one.
  await deps.generationRepo.updateStatus(projectId, generationId, "processing", { incrementAttempt: true });

  try {
    const result = await deps.provider.generateImage(generation.request, (bytes, mimeType, ext) =>
      // The generated bytes are owned by the same project as the generation that asked for
      // them — the only scope under which the resulting asset can later be served.
      deps.assetStore.store(projectId, bytes, mimeType, ext, "image")
    );

    if (result.status !== "succeeded" || !result.images?.length) {
      await deps.generationRepo.updateStatus(projectId, generationId, "failed", {
        providerName: result.providerName,
        errorMessage: result.error ?? "Provider returned no images.",
      });
      return;
    }

    await deps.generationRepo.updateStatus(projectId, generationId, "succeeded", {
      providerName: result.providerName,
      resultAssetId: result.images[0].assetId,
    });
  } catch (err) {
    await deps.generationRepo.updateStatus(projectId, generationId, "failed", {
      errorMessage: err instanceof Error ? err.message : String(err),
    });
    throw err;
  }
}
