import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { FastifyInstance, LightMyRequestResponse } from "fastify";
import type { PgliteDb } from "@ai-platform/database";
import { PROJECT_ROLE_PERMISSIONS, type Permission } from "@ai-platform/shared";
import { generateCsrfToken } from "@ai-platform/security";
import { TEST_PASSWORD, buildTestApp, closeTestApp } from "../test-app.js";
import type { AppContext } from "../context.js";
import { CSRF_COOKIE, CSRF_HEADER, SESSION_COOKIE } from "../plugins/auth.js";

/**
 * docs/API.md, checked against the server — docs/26_DECISIONS.md ADR-112.
 *
 * API.md is generated by scraping the route files, and the first generator published six wrong
 * rows while agreeing perfectly with itself: dead-letter replay as administrator-only (any editor
 * can replay), login and logout as needing a credential, `me` and `projects` as `project:admin`,
 * and one route's 300/minute limit as its neighbour's 30. Regenerating could never catch that. A
 * request can: every row below is sent to the real app, and the document must describe what
 * actually happens — who is let in, who is refused and how, and what rate limit applies.
 */
interface Row {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  auth: string;
  rate: string;
}

const API_MD = join(dirname(fileURLToPath(import.meta.url)), "../../../docs/API.md");
const ROW = /^\| `(GET|POST|PUT|PATCH|DELETE)` \| `([^`]+)` \| (.+?) \| (.+?) \|$/;
const rows: Row[] = readFileSync(API_MD, "utf8")
  .split(/\r?\n/)
  .flatMap((line) => {
    const m = ROW.exec(line);
    return m ? [{ method: m[1] as Row["method"], path: m[2], auth: m[3], rate: m[4] }] : [];
  });

/** A well-formed id that names nothing, so no request below can act on real data. */
const ABSENT_ID = "7d8f3c2e-1b4a-4c6d-9e8f-0a1b2c3d4e5f";

const errorMessage = (res: LightMyRequestResponse): string => {
  try {
    return (res.json() as { error?: { message?: string } }).error?.message ?? "";
  } catch {
    return "";
  }
};


/**
 * Every route the app really has, as "METHOD /path" — ADR-152.
 *
 * Fastify prints its router as a tree whose children carry only their own segment, so the full
 * path is the concatenation of the ancestors' segments. `HEAD` is dropped: Fastify adds it
 * automatically for every `GET` and documenting it would be documenting a framework detail.
 */
function registeredRoutes(app: FastifyInstance): string[] {
  const out: string[] = [];
  const stack: string[] = [];
  for (const line of app.printRoutes({ commonPrefix: false }).split("\n")) {
    const marker = /[├└]── /.exec(line);
    if (!marker) continue;
    const depth = Math.floor(marker.index / 4);
    const body = line.slice(marker.index + marker[0].length);
    const parsed = /^(\S*)\s*\(([^)]*)\)\s*$/.exec(body);
    // A branch node with no methods of its own still contributes its segment to its children.
    const segment = parsed ? parsed[1] : body.trim();
    stack.length = depth;
    stack.push(segment);
    if (!parsed) continue;
    const full = stack.join("");
    for (const method of parsed[2].split(",").map((m) => m.trim())) {
      if (method === "HEAD" || method === "OPTIONS" || method === "") continue;
      out.push(`${method} ${full}`);
    }
  }
  return out;
}

describe("docs/API.md against the running server", () => {
  let app: FastifyInstance;
  let db: PgliteDb;
  let ctx: AppContext;
  let auth: Awaited<ReturnType<typeof buildTestApp>>["auth"];
  let viewerHeaders: Record<string, string>;

  const concrete = (path: string) =>
    path.replace(":projectId", auth.projectId).replace(":queue", "image.generate").replace(/:[A-Za-z]+/g, ABSENT_ID);

  /**
   * Logout ends the session it is sent with, and every later row depends on that session. It is
   * always sent anonymously: if API.md ever mislabelled it as protected, sending it with a session
   * would turn one wrong row into a cascade of 401s that hides which row was actually wrong. The
   * first test still checks its access, which is the one thing anonymity can check.
   */
  const endsSession = (row: Row) => row.method === "POST" && row.path === "/api/v1/auth/logout";

  // Every body is `{}`: enough to reach a guard, and invalid for every route that would act on one.
  const send = (row: Row, headers?: Record<string, string>) =>
    app.inject({
      method: row.method,
      url: concrete(row.path),
      headers: endsSession(row) ? undefined : headers,
      ...(row.method === "GET" ? {} : { payload: {} }),
    });

  beforeAll(async () => {
    ({ app, db, ctx, auth } = await buildTestApp());

    // A real viewer, invited through the real members route.
    const email = `viewer-${Date.now()}@example.test`;
    await ctx.auth.signup({ email, password: TEST_PASSWORD, displayName: "Viewer", organizationName: "Viewer Org" });
    const invited = await app.inject({
      method: "POST",
      url: `/api/v1/projects/${auth.projectId}/members`,
      headers: auth.headers,
      payload: { email, role: "viewer" },
    });
    expect(invited.statusCode).toBe(201);
    const session = await ctx.auth.login(email, TEST_PASSWORD);
    const csrf = generateCsrfToken();
    viewerHeaders = {
      cookie: `${SESSION_COOKIE}=${session.token}; ${CSRF_COOKIE}=${csrf}`,
      [CSRF_HEADER]: csrf,
      "x-project-id": auth.projectId,
    };
  });

  afterAll(async () => {
    await closeTestApp(app, db, ctx);
  });

  it("parses the document at all", () => {
    // A parse that silently matched nothing would make every test below vacuous.
    expect(rows.length).toBeGreaterThanOrEqual(50);
    expect(rows.some((r) => r.auth === "public")).toBe(true);
    expect(rows.some((r) => r.auth.startsWith("system administrator"))).toBe(true);
  });

  it("documents every route the server registers, and registers every route it documents", () => {
    /**
     * Set equality against the REAL route table — docs/26_DECISIONS.md ADR-152.
     *
     * This assertion used to be `rows.length >= 50`. It never enumerated the server's routes, so
     * it could not detect one that was missing from the document — and every other test in this
     * file drives requests FROM the document, so an undocumented route was exercised by none of
     * the auth, permission or rate-limit checks and the count stayed above fifty either way. The
     * only thing enforcing completeness was a CI step, in a workflow this environment has never
     * been able to run.
     */
    const registered = registeredRoutes(app);
    // The walker itself must not silently find nothing.
    expect(registered.length).toBeGreaterThanOrEqual(50);

    const documented = new Set(rows.map((r) => `${r.method} ${r.path}`));
    const live = new Set(registered);

    const undocumented = [...live].filter((r) => !documented.has(r)).sort();
    const phantom = [...documented].filter((r) => !live.has(r)).sort();

    expect({ undocumented, phantom }).toEqual({ undocumented: [], phantom: [] });
  });

  it("lets an anonymous caller reach every public route, and refuses one with 401 everywhere else", async () => {
    const wrong: string[] = [];
    for (const row of rows) {
      const res = await send(row);
      const isPublic = row.auth === "public";
      if (isPublic ? res.statusCode === 401 : res.statusCode !== 401) {
        wrong.push(`${row.method} ${row.path}: documented "${row.auth}", anonymous caller got ${res.statusCode}`);
      }
    }
    expect(wrong).toEqual([]);
  });

  it("enforces exactly the access each route documents", async () => {
    const viewerHas = new Set<Permission>(PROJECT_ROLE_PERMISSIONS.viewer);
    const wrong: string[] = [];
    for (const row of rows) {
      if (row.auth === "public" || endsSession(row)) continue;
      const res = await send(row, viewerHeaders);
      const at = `${row.method} ${row.path}: documented "${row.auth}", a viewer got ${res.statusCode} "${errorMessage(res)}"`;
      const permission = /`([a-z]+:[a-z]+)`/.exec(row.auth)?.[1] as Permission | undefined;

      if (row.auth.startsWith("system administrator")) {
        // The administrator guard's own answer. A mislabelled route would also 404 here — for an
        // absent id — so the message is what tells the two apart.
        if (res.statusCode !== 404 || errorMessage(res) !== "Not found.") wrong.push(at);
      } else if (permission && !viewerHas.has(permission)) {
        if (res.statusCode !== 403 || !errorMessage(res).includes(`"${permission}"`)) wrong.push(at);
      } else if (res.statusCode === 401 || res.statusCode === 403) {
        // Documented as reachable by a viewer: an authentication-only route, or one needing a
        // permission the viewer role has.
        wrong.push(at);
      }
    }
    expect(wrong).toEqual([]);
  });

  it("applies exactly the rate limit each route documents", async () => {
    const expectedLimit = (rate: string): number => {
      const global = /^global \((\d+) \//.exec(rate);
      if (global) return Number(global[1]);
      const configured = /^(?:(\d+) × )?`AUTH_RATE_LIMIT_MAX` \//.exec(rate);
      if (configured) return (configured[1] ? Number(configured[1]) : 1) * ctx.authRateLimitMax;
      const fixed = /^(\d+) \//.exec(rate);
      if (fixed) return Number(fixed[1]);
      throw new Error(`docs/API.md has a rate limit this test cannot read: "${rate}"`);
    };

    const wrong: string[] = [];
    for (const row of rows) {
      // Public routes are sent anonymously — never logout with the owner's session, which the
      // requests after it depend on.
      const res = await send(row, row.auth === "public" ? undefined : auth.headers);
      const actual = res.headers["x-ratelimit-limit"];
      if (String(actual) !== String(expectedLimit(row.rate))) {
        wrong.push(`${row.method} ${row.path}: documented "${row.rate}", server applied ${String(actual)}`);
      }
    }
    expect(wrong).toEqual([]);
  });
});
