import { z } from "zod";

/**
 * Provider-agnostic image generation types — docs/05_IMAGE_GENERATION_RESEARCH.md §4's
 * interface design, adapted to this codebase's conventions. `getCapabilities()` is
 * load-bearing per that doc: no two real providers support the same parameter set, so
 * callers check capabilities rather than assuming a parameter is honored.
 */
export const aspectRatioSchema = z.enum(["1:1", "3:2", "2:3", "4:3", "3:4", "16:9", "9:16"]);
export type AspectRatio = z.infer<typeof aspectRatioSchema>;

export const imageGenerationRequestSchema = z.object({
  prompt: z.string().min(1),
  negativePrompt: z.string().optional(),
  aspectRatio: aspectRatioSchema.default("1:1"),
  seed: z.number().int().optional(),
  quality: z.enum(["fast", "standard", "high"]).default("fast"),
});
export type ImageGenerationRequest = z.infer<typeof imageGenerationRequestSchema>;

export interface GeneratedImage {
  assetId: string;
  width: number;
  height: number;
  seed?: number;
}

export interface ImageResult {
  status: "succeeded" | "failed";
  images?: GeneratedImage[];
  error?: string;
  providerName: string;
  providerMeta?: Record<string, unknown>;
}

export interface ImageProviderCapabilities {
  supportsNegativePrompt: boolean;
  supportsSeed: boolean;
  maxImagesPerCall: number;
  supportedAspectRatios: AspectRatio[];
  hasFastTier: boolean;
  /**
   * How many generations may usefully run at once; absent means no stated limit. A local CPU
   * diffusion model states 1: a second concurrent run gains nothing on the same cores and
   * doubles memory — two SDXL runs beside a 7B chat model drove a 15 GB machine into the OOM
   * killer in the autonomous-completion pass's acceptance run.
   */
  maxConcurrency?: number;
  /** The provider's own ceiling for one generation, when it has one (see the video field). */
  worstCaseDeadlineMs?: number;
}

/** `store` receives the raw generated bytes and returns a durable asset id — the provider
 * itself never touches storage directly, keeping it swappable independent of where/how
 * assets are persisted (local filesystem now, object storage later — docs/19). */
export interface ImageProvider {
  readonly name: string;
  readonly isMock: boolean;
  getCapabilities(): ImageProviderCapabilities;
  generateImage(
    req: ImageGenerationRequest,
    store: (bytes: Buffer, mimeType: string, ext: string) => Promise<string>
  ): Promise<ImageResult>;
}
